### ISSUE TITLE
Format of SEO.set parameter: why no simpler syntax?

### ISSUE THREAD

**Issue by voodoohop** [DerMambo/ms-seo#3]
couldn't we just define the parameters like this? without arrays using the associative array directly. i assume in the head section order doesn't matter and we wouldn't need to define same name'd attributes multiple times

```
SEO.set
  title: data.name
  meta: 
    description: data.description
  og: 
    title: data.name
    description: data.description
```
